DROP TABLE if EXISTS TBL_EMPLOYEES;
DROP TABLE if EXISTS TBL_POSTS;
DROP TABLE if EXISTS TBL_PHONE_NUMBERS;
DROP TABLE if EXISTS TBL_ROOMS;
DROP TABLE if EXISTS TBL_DEPARTMENTS;
DROP TABLE if EXISTS TBL_EMPLOYEE_POST;

CREATE TABLE TBL_POSTS (
  id   INTEGER NOT NULL AUTO_INCREMENT,
  post VARCHAR(128) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE TBL_PHONE_NUMBERS (
    id   INTEGER NOT NULL AUTO_INCREMENT,
    phone_number VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE TBL_DEPARTMENTS (
    id   INTEGER NOT NULL AUTO_INCREMENT,
    department VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE TBL_ROOMS (
    id   INTEGER NOT NULL AUTO_INCREMENT,
    room VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE TBL_EMPLOYEES(
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  patronymic VARCHAR(100) NOT NULL,
  birthday DATE NOT NULL,
  icon_name VARCHAR(200) DEFAULT '',
  phone_number_id INTEGER NOT NULL,
  room_id INTEGER NOT NULL,
  department_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (phone_number_id) REFERENCES TBL_PHONE_NUMBERS(id),
  FOREIGN KEY (room_id) REFERENCES TBL_ROOMS(id),
  FOREIGN KEY (department_id) REFERENCES TBL_DEPARTMENTS(id)
);

CREATE TABLE TBL_EMPLOYEE_POST (
    employee_id INTEGER NOT NULL,
    post_id INTEGER NOT NULL,
    FOREIGN KEY (employee_id) REFERENCES TBL_EMPLOYEES(id),
    FOREIGN KEY (post_id) REFERENCES TBL_POSTS(id),
    PRIMARY KEY (employee_id, post_id)
);

